
from typing import List, Optional
from datetime import datetime
from CustomEnum.EmojiEnum import EmojiCreation2
import copy
class PlantItem:
    def __init__(self, hour_require: int, plant_date: datetime, source_item: "Item", des_item: "Item"):
        self.hour_require = hour_require
        self.plant_date = plant_date
        self.source_item = source_item
        self.des_item = des_item
        
    def to_dict(self):
        return {
            "hour_require": self.hour_require,
            "plant_date": self.plant_date,
            "source_item": self.source_item.to_dict() if self.source_item else None,
            "des_item": self.des_item.to_dict() if self.des_item else None,
        }

    @staticmethod
    def from_dict(data:dict):
        return PlantItem(
                hour_require=data.get("hour_require", 1),
                plant_date=data.get("plant_date", None),
                source_item = Item.from_dict(data.get("source_item", None)) if data.get("source_item") else None,
                des_item = Item.from_dict(data.get("des_item", None)) if data.get("des_item") else None,
            )

    
class Item:
    def __init__(self, item_id: str, item_name: str, item_description: str, item_type: str, quantity: int, emoji: str, item_worth_amount: int = 5000, item_worth_type: str = "C", item_require_target: bool = False, is_self_usable = False, bonus_exp: int = 0, bonus_dignity: int = 0, rank_required: int = 1):
        self.item_id = item_id
        self.item_name = item_name
        self.item_description = item_description
        self.item_type = item_type
        self.quantity = quantity
        self.emoji = emoji
        self.item_worth_amount = item_worth_amount
        self.item_worth_type = item_worth_type
        self.item_require_target = item_require_target
        self.is_self_usable = is_self_usable
        self.bonus_exp = bonus_exp
        self.bonus_dignity = bonus_dignity
        self.rank_required = rank_required

    def to_dict(self):
        return {
            "item_id": self.item_id,
            "item_name": self.item_name,
            "item_description": self.item_description,
            "item_type": self.item_type,
            "quantity": self.quantity,
            "emoji": self.emoji,
            "item_worth_amount": self.item_worth_amount,
            "item_worth_type": self.item_worth_type,
            "item_require_target": self.item_require_target,
            "is_self_usable": self.is_self_usable,
            "bonus_exp": self.bonus_exp,
            "bonus_dignity": self.bonus_dignity,
            "rank_required": self.rank_required,
        }

    @staticmethod
    def from_dict(data:dict):
        return Item(
                item_id=data.get("item_id", None),
                item_name=data.get("item_name", None),
                item_description=data.get("item_description", None),
                item_type=data.get("item_type", None),
                quantity=data.get("quantity", None),
                emoji=data.get("emoji", None),
                item_worth_amount=data.get("item_worth_amount", None),
                item_worth_type=data.get("item_worth_type", None),
                
                item_require_target=data.get("item_require_target", False),
                is_self_usable=data.get("is_self_usable", False),
                
                bonus_exp=data.get("bonus_exp", 0),
                bonus_dignity=data.get("bonus_dignity", 0),
                rank_required=data.get("rank_required", 1),
            )

#region list gift
list_gift_items_p = [
    Item(
        item_id = "g_pocky",
        item_name = "Bánh Pocky",
        item_description = "Hộp bánh pocky sẽ giúp bạn tăng kinh nghiệm khi tặng cho người khác!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.GIFT_POCKY.value,
        item_worth_amount = 30,
        item_worth_type= "S",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 0,
        rank_required = 1,
    ),
    Item(
        item_id = "g_flower",
        item_name = "Hoa Xinh",
        item_description = "Bông hoa quý báu có thể giúp tăng nhân phẩm và kinh nghiệm khi tặng cho người khác! Hoặc biết đâu sẽ khiến họ vui hơn thì sao?",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.GIFT_FLOWER.value,
        item_worth_amount = 50,
        item_worth_type= "S",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 5,
        rank_required = 5,
    ),
    Item(
        item_id = "g_chocolate",
        item_name = "Sô cô la",
        item_description = "Một thanh sô cô la ngon lành sẽ làm tăng nhân phẩm và kinh nghiệm khi tặng cho người khác!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.GIFT_CHOCOLATE.value,
        item_worth_amount = 50,
        item_worth_type= "S",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 5,
        bonus_dignity = 10,
        rank_required = 8,
    ),
    Item(
        item_id = "g_stcake",
        item_name = "Bánh kem dâu",
        item_description = "Một miếng bánh kem dâu ngon miệng sẽ làm tăng nhân phẩm và kinh nghiệm khi tặng cho người khác!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.GIFT_STRAW_CAKE.value,
        item_worth_amount = 75,
        item_worth_type= "S",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 10,
        rank_required = 10,
    ),
    Item(
        item_id = "g_earring",
        item_name = "Khuyên Tai Bạc",
        item_description = "Một đôi khuyên tai xinh xinh cho bạn gái, có thể giúp tăng nhân phẩm và kinh nghiệm khi tặng!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.GIFT_EARRING.value,
        item_worth_amount = 100,
        item_worth_type= "S",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 15,
        bonus_dignity = 5,
        rank_required = 20,
    ),
    Item(
        item_id = "g_sring",
        item_name = "Nhẫn Bạc",
        item_description = "Nhẫn bạc quý phái và đầy thanh lịch, một món quà hoàn hảo có thể giúp tăng nhân phẩm và kinh nghiệm khi tặng cho người khác!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.GIFT_SILVER_RING.value,
        item_worth_amount = 500,
        item_worth_type= "S",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 15,
        bonus_dignity = 10, 
        rank_required = 25,
    ),
    Item(
        item_id = "g_gring",
        item_name = "Nhẫn Vàng",
        item_description = "Nhẫn vàng quý tộc và giàu sang, một món quà hoàn hảo có thể giúp tăng nhân phẩm và kinh nghiệm khi tặng cho người khác!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.GIFT_GOLD_RING.value,
        item_worth_amount = 20,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 30,
        bonus_dignity = 15,
        rank_required = 25,
    ),
    Item(
        item_id = "g_dring",
        item_name = "Nhẫn Kim Cương",
        item_description = "Nhẫn kim cương hào nhoáng và phú quý, một món quà hoàn hảo có thể giúp tăng nhân phẩm và kinh nghiệm khi tặng cho người khác!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.GIFT_DIAMOND_RING.value,
        item_worth_amount = 120,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 30,
        bonus_dignity = 20,
        rank_required = 35,
    ),
]
list_gift_items = copy.deepcopy(list_gift_items_p)
#region list protection
list_protection_items_p = [
    Item(
        item_id = "hat_fight_1",
        item_name = "Mũ Chống Đánh",
        item_description = "Mũ bảo hiểm giúp chống bị người khác động thủ, chỉ dùng một lần!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.HELMET_1.value,
        item_worth_amount = 1000,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 15,
    ),
    Item(
        item_id = "hat_fight_2",
        item_name = "Mũ Phản Phệ",
        item_description = "Mũ bảo hiểm giúp đánh ngược lại đứa nào dám đánh luôn cả mình!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.HELMET_2.value,
        item_worth_amount = 6000,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 18,
    ),
    Item(
        item_id = "armor_rob_1",
        item_name = "Giáp Chống Cướp",
        item_description = "Giáp hộ vệ bảo vệ bản thân khỏi lũ cướp ngày!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.ARMOUR_1.value,
        item_worth_amount = 10000,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 18,
    ),
    Item(
        item_id = "armor_rob_2",
        item_name = "Giáp Phản Cướp",
        item_description = "Giáp hộ vệ bảo vệ bản thân khỏi lũ cướp và cướp ngược lại lũ đấy!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.ARMOUR_2.value,
        item_worth_amount = 25000,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 20,
    ),
    Item(
        item_id = "armor_protection_1",
        item_name = "Giáp Da",
        item_description = "Giáp hộ vệ linh hoạt chống vũ khí rẻ tiền, chỉ có 50% bảo vệ thành công!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.ARMOUR_PROTECTION_1.value,
        item_worth_amount = 400,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 35,
    ),
    Item(
        item_id = "armor_protection_2",
        item_name = "Thiết Giáp",
        item_description = "Giáp hộ vệ linh hoạt chống vũ khí!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.ARMOUR_PROTECTION_2.value,
        item_worth_amount = 1000,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 40,
    ),
    Item(
        item_id = "armor_protection_3",
        item_name = "Giáp Nhân Phẩm",
        item_description = "Giáp hộ vệ chống vũ khí và trừ thêm **20** nhân phẩm của kẻ tấn công!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.ARMOUR_PROTECTION_3.value,
        item_worth_amount = 2000,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 40,
    ),
    Item(
        item_id = "armor_protection_4",
        item_name = "Vệ Giáp",
        item_description = f"Giáp hộ vệ chống vũ khí và trừ tiền {EmojiCreation2.COPPER.value} của kẻ tấn công!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.ARMOUR_PROTECTION_4.value,
        item_worth_amount = 3000,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 50,
    ),
    Item(
        item_id = "armor_protection_5",
        item_name = "Giáp Hạng Nặng",
        item_description = f"Giáp hộ vệ chống vũ khí và trừ tiền {EmojiCreation2.SILVER.value} hoặc 10% tỉ lệ tăng rank của kẻ tấn công!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.ARMOUR_PROTECTION_5.value,
        item_worth_amount = 4000,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 50,
    ),
]
list_protection_items = copy.deepcopy(list_protection_items_p)
#region list support item
list_support_items_p = [
    Item(
        item_id = "rank_up_1",
        item_name = "Thần Dược",
        item_description = "Thần dược tuyệt đối, giúp tăng rank của bản thân lên một cấp!",
        item_type = "self_support",
        quantity = 1,
        emoji = EmojiCreation2.COLORFUL_PILL.value,
        item_worth_amount = 7,
        item_worth_type= "D",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 1,
    ),
    Item(
        item_id = "rank_down_1",
        item_name = "Tiệt Phế Dược",
        item_description = "Đả dược có tác dụng tự phế một rank của bản thân!",
        item_type = "self_support",
        quantity = 1,
        emoji = EmojiCreation2.PILL.value,
        item_worth_amount = 7,
        item_worth_type= "D",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 1,
    ),
    Item(
        item_id = "lock_pick_jail",
        item_name = "Bẻ khoá",
        item_description = "Dụng cụ bẻ khoá, giúp thoát giam lỏng lệnh! Nếu không bị bắt thì không hề vi phạm luật pháp!",
        item_type = "self_support",
        quantity = 1,
        emoji = EmojiCreation2.LOCKPICK.value,
        item_worth_amount = 50,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 20,
    ),
    Item(
        item_id = "out_jail_ticket",
        item_name = "Thẻ Ra Tù",
        item_description = "Chúc mừng bạn đã quay vào ô ra tù miễn phí!",
        item_type = "self_support",
        quantity = 1,
        emoji = EmojiCreation2.TICKET.value,
        item_worth_amount = 100,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 20,
    ),
    Item(
        item_id = "forget_flower",
        item_name = "Hoa Lãng Quên",
        item_description = "Bảo bối giúp lãng quên đi mối tình sâu đậm khi xưa! Sẽ cho phép bạn quen người mới ngay lập tức",
        item_type = "self_support",
        quantity = 1,
        emoji = EmojiCreation2.PURPLE_FLOWER.value,
        item_worth_amount = 500,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 25,
    ),
    Item(
        item_id = "trash_cot_use",
        item_name = "Phân bón",
        item_description = "Một đống xương dính cớt, nhưng có thể dùng làm phân bón cho cây trồng để tăng tiến trình trồng!",
        item_type = "self_support",
        quantity = 1,
        emoji = EmojiCreation2.SHIT.value,
        item_worth_amount = 50,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 5,
        rank_required = 1,
    ),
    Item(
        item_id = "search_warrant",
        item_name = "Lệnh khám xét",
        item_description = "Lệnh khám xét đặc cách cho phép người sở hữu được quyền điều tra bất kỳ ai, kể cả Chính Quyền",
        item_type = "misc",
        quantity = 1,
        emoji = EmojiCreation2.CERT_2.value,
        item_worth_amount = 100,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 20,
    ),
]
list_support_items = copy.deepcopy(list_support_items_p)
list_support_ga_items_p= [
    Item(
        item_id = "ga_heal_1",
        item_name = "Lọ Hồi Máu Nhỏ",
        item_description = "Một lọ thuốc nhỏ giúp hồi 30% máu cho Hộ Vệ Thần! Nếu Hộ Vệ Thần đã bị trọng thương sẽ hồi phục lại được!",
        item_type = "self_support",
        quantity = 1,
        emoji = EmojiCreation2.POTION_HP_1.value,
        item_worth_amount = 350,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 10,
    ),
    Item(
        item_id = "ga_stamina_1",
        item_name = "Lọ Hồi Thể Lực Nhỏ",
        item_description = "Một lọ thuốc nhỏ giúp hồi 50% thể lực cho Hộ Vệ Thần!",
        item_type = "self_support",
        quantity = 1,
        emoji = EmojiCreation2.POTION_STAMINA_1.value,
        item_worth_amount = 250,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 10,
    ),
    Item(
        item_id = "ga_mana_1",
        item_name = "Lọ Hồi Mana Nhỏ",
        item_description = "Một lọ thuốc nhỏ giúp hồi 50% Mana cho Hộ Vệ Thần!",
        item_type = "self_support",
        quantity = 1,
        emoji = EmojiCreation2.POTION_MANA_1.value,
        item_worth_amount = 200,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 10,
    ),
    Item(
        item_id = "ga_all_restored",
        item_name = "Đại Phục Hồi",
        item_description = "Một lọ đại dược giúp hồi phục toàn bộ chỉ số của Hộ Vệ Thần!",
        item_type = "self_support",
        quantity = 1,
        emoji = EmojiCreation2.POTION_ALL.value,
        item_worth_amount = 40,
        item_worth_type= "D",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 1,
    ),
    Item(
        item_id = "ga_resurrection",
        item_name = "Phục Sinh Thạch",
        item_description = "Một tảng đá thần kỳ giúp hồi sinh Hộ Vệ Thần từ cõi chết! Đôi khi, chết vẫn chưa là hết!",
        item_type = "self_support",
        quantity = 1,
        emoji = EmojiCreation2.MAGIC_DV.value,
        item_worth_amount = 60,
        item_worth_type= "D",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 1,
    ),
]
list_support_ga_items = copy.deepcopy(list_support_ga_items_p)

#region list attack items
list_attack_items_p = [
    Item(
        item_id = "crime_evident",
        item_name = "Bằng Chứng Phạm Tội",
        item_description = f"Hàng cấm, có thể bị chính quyền điều tra ra! Tốt nhất nên nằm trong túi của người khác!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.BLOODY_KNIFE.value,
        item_worth_amount = 500,
        item_worth_type= "S",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 35,
    ),
    Item(
        item_id = "whipping",
        item_name = "Dây Roi",
        item_description = f"Dây roi để quật những kẻ lười biếng phải lao động, và trừ 10 nhân phẩm của kẻ đó!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.WHIP.value,
        item_worth_amount = 500,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 40,
    ),
    Item(
        item_id = "sword_1",
        item_name = "Kiếm Gỗ",
        item_description = "Một thanh kiếm gỗ bình thường, có thể chém bay nhân phẩm của đối thủ!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.SWORD_1.value,
        item_worth_amount = 700,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 50,
    ),
    Item(
        item_id = "sword_2",
        item_name = "Kiếm Đồng",
        item_description = f"Một thanh kiếm đồng rẻ tiền có thể chém bay tiền {EmojiCreation2.COPPER.value} của đối thủ!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.SWORD_2.value,
        item_worth_amount = 800,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 50,
    ),
    Item(
        item_id = "sword_3",
        item_name = "Kiếm Sắt",
        item_description = f"Một thanh kiếm sắt bình thường có thể chém bay tiền Copper hoặc điểm nhân phẩm của đối thủ!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.SWORD_3.value,
        item_worth_amount = 1000,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 50,
    ),
    Item(
        item_id = "sword_4",
        item_name = "Kiếm Bạc",
        item_description = f"Một thanh kiếm bạc đắt giá có thể chém bay tiền Copper hoặc 10% tăng rank của đối thủ!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.SWORD_4.value,
        item_worth_amount = 2600,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 55,
    ),
    Item(
        item_id = "sword_5",
        item_name = "Kiếm Vàng",
        item_description = f"Một thanh kiếm bạc đắt giá có thể chém bay tiền Silver hoặc 15% tăng rank của đối thủ!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.SWORD_5.value,
        item_worth_amount = 5200,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 55,
    ),
    Item(
        item_id = "crime_knife",
        item_name = "Dao Ẩn",
        item_description = f"Một lưỡi dao ẩn có thể chém đứt khả năng phạm tội của đối phương trong một tiếng!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.KNIFE.value,
        item_worth_amount = 1200,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 40,
    ),
    Item(
        item_id = "cuff",
        item_name = "Còng Tay",
        item_description = f"Vật phẩm dành riêng cho chính quyền, nhằm trấn áp những kẻ tình nghi phạm tội trong hai tiếng!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.HANDCUFF.value,
        item_worth_amount = 2000,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 40,
    ),
]
list_attack_items = copy.deepcopy(list_attack_items_p)
#Misc
#region Fishing rod
list_fishing_rod_p = [
    Item(
        item_id = "fish_rod_1",
        item_name = "Cần Câu Nhựa",
        item_description = f"Cần dùng để câu cá, chất lượng thấp nhất, chỉ câu được cá nhỏ xíu!",
        item_type = "misc",
        quantity = 1,
        emoji = EmojiCreation2.FISHING_ROD_1.value,
        item_worth_amount = 10000,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 5,
    ),
    Item(
        item_id = "fish_rod_2",
        item_name = "Cần Câu Gỗ",
        item_description = f"Cần câu bình thường có thể câu cá nhỏ đến lớn!",
        item_type = "misc",
        quantity = 1,
        emoji = EmojiCreation2.FISHING_ROD_2.value,
        item_worth_amount = 25000,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 5,
    ),
    Item(
        item_id = "fish_rod_3",
        item_name = "Cần Câu Tre",
        item_description = f"Cần câu khá tốt có thể câu mọi loại cá!",
        item_type = "misc",
        quantity = 1,
        emoji = EmojiCreation2.FISHING_ROD_3.value,
        item_worth_amount = 25,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 10,
    ),
    Item(
        item_id = "fish_rod_4",
        item_name = "Cần Câu Lướt",
        item_description = f"Cần câu xịn nhất, có thể câu nhiều con cá cùng một lúc, và có thể câu cả châu báu!",
        item_type = "misc",
        quantity = 1,
        emoji = EmojiCreation2.FISHING_ROD_4.value,
        item_worth_amount = 10,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 15,
    ),
    Item(
        item_id = "fish_rod_5",
        item_name = "Bom Đánh Cá",
        item_description = f"Cần câu, à không, quên mấy cần câu đi, đây mới là thứ đánh cá xịn nhất, có thể lụm được nhiều con cá cùng một lúc, nhưng đừng quên nó là hàng cấm đấy nhé! Đừng để bị bắt",
        item_type = "misc",
        quantity = 1,
        emoji = EmojiCreation2.FISHING_ROD_5.value,
        item_worth_amount = 50,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 15,
    ),
    
    Item(
        item_id = "seed_wheat",
        item_name = "Hạt giống lúa",
        item_description = f"Hạt giống lúa mạch, sẽ phát triển thành cây lúa sau một tiếng đồng hồ",
        item_type = "seed",
        quantity = 1,
        emoji = EmojiCreation2.SEED_WHEAT.value,
        item_worth_amount = 10000,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 5,
    ),
    Item(
        item_id = "seed_potato",
        item_name = "Hạt giống khoai tây",
        item_description = f"Hạt giống khoai tây, sẽ phát triển thành khoai tây siêu to sau hai tiếng, vì khoai to không lo chết đói!",
        item_type = "seed",
        quantity = 1,
        emoji = EmojiCreation2.SEED_POTATO.value,
        item_worth_amount = 50,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 5,
    ),
    Item(
        item_id = "seed_corn",
        item_name = "Hạt giống ngô",
        item_description = f"Hạt giống ngô, sẽ phát triển thành củ ngô sau hai tiếng!",
        item_type = "seed",
        quantity = 1,
        emoji = EmojiCreation2.SEED_CORN.value,
        item_worth_amount = 40,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 5,
    ),
    Item(
        item_id = "seed_watermelon",
        item_name = "Hạt dưa hấu",
        item_description = f"Hạt giống dưa hấu, sẽ phát triển thành trái dưa to sau ba tiếng!",
        item_type = "seed",
        quantity = 1,
        emoji = EmojiCreation2.SEED_WATERMELON.value,
        item_worth_amount = 60,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 5,
    ),
    Item(
        item_id = "seed_weed",
        item_name = "Hạt Sà Cân",
        item_description = f"Hạt cần, khi cần sẽ có sau ba tiếng trồng!",
        item_type = "seed",
        quantity = 1,
        emoji = EmojiCreation2.SEED_WATERMELON.value,
        item_worth_amount = 100,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 5,
    ),
]
list_fishing_rod = copy.deepcopy(list_fishing_rod_p)
list_plant_p = [
    Item(
        item_id = "wheat",
        item_name = "Cây lúa",
        item_description = "Từ nơi đồng xanh thơm hương lúa!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.WHEAT.value,
        item_worth_amount = 4000,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 5,
        bonus_dignity = 5,
        rank_required = 1,
    ),
    Item(
        item_id = "potato",
        item_name = "Củ khoai tây",
        item_description = "Củ khoai tây siêu to không lo chết đói!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.POTATO.value,
        item_worth_amount = 25,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 15,
        bonus_dignity = 5,
        rank_required = 1,
    ),
    Item(
        item_id = "corn",
        item_name = "Trái bắp",
        item_description = "Một trái bắp ngon lành!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.CORN.value,
        item_worth_amount = 25,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 15,
        bonus_dignity = 5,
        rank_required = 1,
    ),
    Item(
        item_id = "watermelon",
        item_name = "Trái dưa hấu",
        item_description = "Một trái dưa hấu mọng nước ngon lành!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.WATERMELON.value,
        item_worth_amount = 30,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 15,
        bonus_dignity = 5,
        rank_required = 1,
    ),
    Item(
        item_id = "weed",
        item_name = "Cần Sa",
        item_description = "Một tý cỏ cho đời thêm xanh chín, đừng để Chính Quyền bắt gặp bạn sở hữu thứ cỏ kỳ diệu này!",
        item_type = "self_support",
        quantity = 1,
        emoji = EmojiCreation2.WEED.value,
        item_worth_amount = 50,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 120,
        bonus_dignity = 10,
        rank_required = 1,
    ),
]
list_plant = copy.deepcopy(list_plant_p)
#region trash
list_trash_p = [
    Item(
        item_id = "trash_shirt",
        item_name = "Áo rách",
        item_description = "Một cái áo jack nát tan tành!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.SHIRT.value,
        item_worth_amount = 50,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 5,
        bonus_dignity = -10,
        rank_required = 1,
    ),
    Item(
        item_id = "trash_cloth",
        item_name = "Vải rách nát",
        item_description = "Một miếng nùi giẻ nhàu nát, jack tan tành như tương lai của bạn!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.CLOTH.value,
        item_worth_amount = 50,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 5,
        bonus_dignity = -15,
        rank_required = 1,
    ),
    Item(
        item_id = "trash_panties",
        item_name = "Quần lót hồng",
        item_description = "Một cái quần lót hồng dính chút màu vàng đã rách nát! Có thể là của waifu của bạn!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.PANTIES_PINK.value,
        item_worth_amount = 50,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 5,
        bonus_dignity = -15,
        rank_required = 1,
    ),
    Item(
        item_id = "trash_panties_2",
        item_name = "Quần lót nam",
        item_description = "Một cái quần xì nam rách nát dính chút màu vàng ố! Có thể là quần của bạn!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.PANTIES_GREY.value,
        item_worth_amount = 50,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 5,
        bonus_dignity = -15,
        rank_required = 1,
    ),
    Item(
        item_id = "trash_cot",
        item_name = "Cớt",
        item_description = "Một đống xương dính cớt!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.SHIT.value,
        item_worth_amount = 50,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = -15,
        rank_required = 1,
    ),
    Item(
        item_id = "trash_cot_use",
        item_name = "Phân bón rác rưởi",
        item_description = "Một đống xương dính cớt, nhưng có thể dùng làm phân bón cho cây trồng để tăng tiến trình trồng!",
        item_type = "self_support",
        quantity = 1,
        emoji = EmojiCreation2.SHIT.value,
        item_worth_amount = 50,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 5,
        rank_required = 1,
    ),
]
list_trash = copy.deepcopy(list_trash_p)
#region copper fish
list_small_copper_fish_p = [
    Item(
        item_id = "small_fish_1",
        item_name = "Cá tép",
        item_description = "Cơ thể nhỏ bé, trong suốt, có nhiều màu sắc sặc sỡ. Chúng thường sống thành đàn lớn trong các hồ, ao, sông nhỏ!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.SMALL_FISH.value,
        item_worth_amount = 25000,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 5,
        bonus_dignity = 0,
        rank_required = 1,
    ),
    Item(
        item_id = "small_fish_2",
        item_name = "Cá phi con",
        item_description = "Cá có nhiều màu sắc rực rỡ, vây đuôi dài và đẹp. Chúng dễ nuôi và sinh sản nhanh, thường sống thành đàn lớn trong các hồ, ao, sông nhỏ!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.SMALL_FISH.value,
        item_worth_amount = 28000,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 2,
        rank_required = 1,
    ),
    Item(
        item_id = "small_fish_3",
        item_name = "Cá mún",
        item_description = "Cơ thể dài, thon, vây lưng dài và có nhiều gai nhọn. Chúng thường sống ở những vùng nước tĩnh hoặc chảy chậm.",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.SMALL_FISH.value,
        item_worth_amount = 35000,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 2,
        rank_required = 1,
    ),
    Item(
        item_id = "small_fish_4",
        item_name = "Cá trôi con",
        item_description = "Cơ thể dài, thường sống ở các sông, hồ lớn và được sử dụng làm thức ăn cho cá lớn hơn, nuôi để lấy thịt.",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.FISH.value,
        item_worth_amount = 39000,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 2,
        rank_required = 1,
    ),
    Item(
        item_id = "small_fish_5",
        item_name = "Cá chép con",
        item_description = "Cơ thể hình thoi, vảy lớn, màu vàng hoặc nâu. Chúng thường sống ở các ao, hồ, sông.",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.BLUE_FISH.value,
        item_worth_amount = 45000,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 2,
        rank_required = 1,
    ),
    Item(
        item_id = "small_fish_6",
        item_name = "Cá bống xanh lè",
        item_description = "Cơ thể dài, tròn, vây lưng ngắn. Chúng thường sống ở các vùng nước lợ hoặc nước ngọt..",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.FISH_1.value,
        item_worth_amount = 35000,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 4,
        rank_required = 1,
    ),
    Item(
        item_id = "small_fish_7",
        item_name = "Sứa Con",
        item_description = "Cơ thể dài, tròn và không hề có não như ai đó!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.JELLY_FISH.value,
        item_worth_amount = 45000,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 3,
        rank_required = 1,
    ),
    Item(
        item_id = "small_fish_8",
        item_name = "Cá Cô Tiên",
        item_description = "Cơ thể cá nhỏ thon gọn và trông khá dẹt!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.JELLY_FISH.value,
        item_worth_amount = 38000,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 4,
        rank_required = 1,
    ),
    Item(
        item_id = "small_fish_9",
        item_name = "Cá Suy Ngẫm",
        item_description = "Một con cá mãi mê suy ngẫm xem ngày mai nên ăn gì!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.FISH_THINK.value,
        item_worth_amount = 38000,
        item_worth_type= "C",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 4,
        rank_required = 1,
    ),
]
list_small_copper_fish = copy.deepcopy(list_small_copper_fish_p)
#region silver fish
list_silver_fish_p = [
    Item(
        item_id = "medium_fish_1",
        item_name = "Cá Dory",
        item_description = "Một con cá rất hay lãng quên tùm lum thứ, luôn lạc đường và quên mọi thứ rất nhanh.",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.FISH_1.value,
        item_worth_amount = 55,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 5,
        rank_required = 1,
    ),
    Item(
        item_id = "medium_fish_2",
        item_name = "Cá Dory",
        item_description = "Một con cá rất hay lãng quên tùm lum thứ, luôn lạc đường và quên mọi thứ rất nhanh.",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.DORY.value,
        item_worth_amount = 65,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 5,
        rank_required = 1,
    ),
    Item(
        item_id = "medium_fish_3",
        item_name = "Cá Nóc",
        item_description = "Một con cá nóc, được coi là động vật có xương sống độc thứ hai trên thế giới, chỉ sau ếch độc phi tiêu vàng.",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.FISH_NOC.value,
        item_worth_amount = 75,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 5,
        rank_required = 1,
    ),
    Item(
        item_id = "medium_fish_4",
        item_name = "Cá Đỏ",
        item_description = "Một con cá đỏ lạ lùng.",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.RED_FISH.value,
        item_worth_amount = 85,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 5,
        rank_required = 1,
    ),
    Item(
        item_id = "medium_fish_5",
        item_name = "Cá Xanh",
        item_description = "Kích thước của các loài cá trên có thể thay đổi tùy thuộc vào môi trường sống và điều kiện nuôi dưỡng.",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.BLUE_FISH.value,
        item_worth_amount = 100,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 5,
        rank_required = 1,
    ),
    Item(
        item_id = "medium_fish_6",
        item_name = "Rùa Cay Dé",
        item_description = "Một con rùa cay đứa bắt nó đến đỏ người!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.TURTLE_ANGRY.value,
        item_worth_amount = 120,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 5,
        rank_required = 1,
    ),
    Item(
        item_id = "medium_fish_7",
        item_name = "Mồn Lèo Cá",
        item_description = "Một con cá mồn lèo chuyên ăn tạp!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.FISH_BUGCAT.value,
        item_worth_amount = 85,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 5,
        rank_required = 1,
    ),
    Item(
        item_id = "medium_fish_8",
        item_name = "Cá Phóng Xạ",
        item_description = "Một con cá xanh lè trông khá kỳ lạ, ăn vào có thể có siêu sức mạnh, hoặc siêu ung thư!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.FISH_BUGCAT.value,
        item_worth_amount = 90,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 5,
        rank_required = 1,
    ),
    Item(
        item_id = "medium_fish_9",
        item_name = "Cá Chà Bu",
        item_description = "Một con cá trông khá đù, thuộc họ Cam, Cam Mười Tú!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.POG_FISH.value,
        item_worth_amount = 80,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 5,
        rank_required = 1,
    ),
    Item(
        item_id = "medium_fish_10",
        item_name = "Lợn Biển",
        item_description = "Lợn biển có thể nặng hơn nửa tấn, dành 8 tiếng gặm cỏ mỗi ngày và không có kẻ săn mồi trong tự nhiên!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.MANATEE.value,
        item_worth_amount = 95,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 5,
        rank_required = 1,
    ),
    Item(
        item_id = "medium_fish_10",
        item_name = "Lợn Biển",
        item_description = "Lợn biển có thể nặng hơn nửa tấn, dành 8 tiếng gặm cỏ mỗi ngày và không có kẻ săn mồi trong tự nhiên!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.MANATEE.value,
        item_worth_amount = 100,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 5,
        rank_required = 1,
    ),
    Item(
        item_id = "medium_fish_11",
        item_name = "Chim Cánh Cụt Dao",
        item_description = "Mày câu tao thêm lần nữa coi tao có đâm mày không?!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.STAB_PENGUIN.value,
        item_worth_amount = 150,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 20,
        bonus_dignity = 15,
        rank_required = 1,
    ),
]
list_silver_fish = copy.deepcopy(list_silver_fish_p)
#region gold fish
list_gold_fish_p = [
    Item(
        item_id = "big_fish_1",
        item_name = "Cá Mập",
        item_description = "Cá mập có thể đạt tốc độ bơi hơn 56 km/h (35 mph) và thật ra nó không hề mập hơn bạn!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.SHARK.value,
        item_worth_amount = 35,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 20,
        bonus_dignity = 15,
        rank_required = 1,
    ),
    Item(
        item_id = "big_fish_2",
        item_name = "Cá Heo Hồng",
        item_description = "Lũ cá heo đực còn có một tập tính ghê rợn khác, đó là thảm sát cá heo con!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.PINK_DOLPHIN.value,
        item_worth_amount = 40,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 20,
        bonus_dignity = 15,
        rank_required = 1,
    ),
    Item(
        item_id = "big_fish_3",
        item_name = "Cá Heo",
        item_description = "Lũ cá heo có đời sống tình dục mạnh mẽ đến nỗi không chỉ làm chuyện ấy với đồ vật vô tri, các loài động vật khác mà thậm chí còn nghĩ đến chuyện ve vãn con người!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.MC_DOLPHIN.value,
        item_worth_amount = 45,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 20,
        bonus_dignity = 15,
        rank_required = 1,
    ),
    Item(
        item_id = "big_fish_4",
        item_name = "Vịt Đần",
        item_description = "Vịt đần trông stress như bạn lúc deadline dí ngập đầu!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.PANIC_DUCK.value,
        item_worth_amount = 35,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 20,
        bonus_dignity = 15,
        rank_required = 1,
    ),
    Item(
        item_id = "big_fish_5",
        item_name = "Cá Mập Cha",
        item_description = "Một con cá mập dễ thương hiền lành và không mập bằng bạn!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.SHARK_1.value,
        item_worth_amount = 25,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 20,
        bonus_dignity = 15,
        rank_required = 1,
    ),
    Item(
        item_id = "big_fish_6",
        item_name = "Rùa Đỏ Chót",
        item_description = "Một con rùa cay đến đỏ dé!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.TURTLE_ANGRY.value,
        item_worth_amount = 45,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 20,
        bonus_dignity = 5,
        rank_required = 1,
    ),
    Item(
        item_id = "big_fish_8",
        item_name = "Hải Cẩu",
        item_description = "Một con hải cẩu sống dưới biển và ăn nhiều loại cá, chủ yếu là sinh vật đáy hoặc sinh vật sống gần đáy!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.SEAL.value,
        item_worth_amount = 30,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 20,
        bonus_dignity = 15,
        rank_required = 1,
    ),
    Item(
        item_id = "big_fish_9",
        item_name = "Chim Cánh Cụt",
        item_description = "Chim cánh cụt là loài sống theo quần thể, có tính xã hội cao, luôn tập trung theo bầy đàn và thích đóng phim!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.PENGUIN_PEEK.value,
        item_worth_amount = 35,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 20,
        bonus_dignity = 15,
        rank_required = 1,
    ),
    Item(
        item_id = "big_fish_10",
        item_name = "Chim Cánh Cụt Dao Bự",
        item_description = "Mày câu tao thêm lần nữa coi tao có đâm mày không?!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.STAB_PENGUIN.value,
        item_worth_amount = 50,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = False,
        bonus_exp = 20,
        bonus_dignity = 15,
        rank_required = 1,
    ),
]
list_gold_fish = copy.deepcopy(list_gold_fish_p)
#region legend weapons
list_legend_weapon_1_p = [
    Item(
        item_id = "legend_axe",
        item_name = "Hàn Long Phủ",
        item_description = f"Rìu chiến huyền thoại với sức mạnh băng giá có thể đóng băng và phá nát toàn bộ loại giáp kẻ địch đang dùng!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.LEGEND_AXE_1.value,
        item_worth_amount = 1000,
        item_worth_type= "D",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 50,
    ),
    Item(
        item_id = "legend_axe_2",
        item_name = "Đại Kình Lôi Phủ",
        item_description = f"Đại rìu chiến huyền thoại đã thất truyền từ lâu với sức mạnh huỷ diệt 10 cấp của kẻ địch!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.LEGEND_AXE_1.value,
        item_worth_amount = 5000,
        item_worth_type= "D",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 50,
    ),
    Item(
        item_id = "legend_karambit",
        item_name = "Loạn Chiến Đao",
        item_description = f"Đoản đao thất lạc ngàn đời, sức mạnh vô đối có thể chém nát một vũ khí ngẫu nhiên của kẻ địch!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.LEGEND_KARAMBIT.value,
        item_worth_amount = 10000,
        item_worth_type= "D",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 50,
    ),
    Item(
        item_id = "legend_scythe",
        item_name = "Vô Đại Cực Liềm",
        item_description = f"Lưỡi liềm tử thần với sức mạnh hỗn cực có thể hoàn toàn gặt nát hết cả khu vườn lẫn hạt giống của kẻ địch!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.LEGEND_SCYTHES.value,
        item_worth_amount = 5000,
        item_worth_type= "D",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 50,
    ),
]
list_legend_weapon_1 = copy.deepcopy(list_legend_weapon_1_p)
list_legend_weapon_2_p = [
    Item(
        item_id = "legend_spear_1",
        item_name = "Nhất Hàn Đoản Thương",
        item_description = f"Ngọn giáo băng giáo với sức mạnh đóng băng lệnh của kẻ địch trong vòng bốn tiếng!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.LEGEND_SPEAR_1.value,
        item_worth_amount = 1000,
        item_worth_type= "D",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 20,
    ),
    Item(
        item_id = "legend_spear_2",
        item_name = "Thiết Bản Phá Thương",
        item_description = f"Ngọn giáo huyền thoại với sức mạnh phá nát một bộ giáp ngẫu nhiên của kẻ địch!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.LEGEND_SPEAR_2.value,
        item_worth_amount = 1000,
        item_worth_type= "D",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 50,
    ),
    Item(
        item_id = "legend_sword_1",
        item_name = "Cực Xung Nhật Kiếm",
        item_description = f"Một thanh đại kiếm thần thoại uy hồn với sức mạnh của mặt trời có thể chém bốc hơi một phần số tiền lớn nhất của kẻ địch!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.LEGEND_SWORD_1.value,
        item_worth_amount = 6000,
        item_worth_type= "D",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 50,
    ),
    Item(
        item_id = "legend_sword_2",
        item_name = "Hỗn Cực Hoả Kiếm",
        item_description = f"Một thanh trường kiếm huyền thoại có thể thiêu rụi nhân phẩm và mọi tiến trình của kẻ địch để chuyển thành kinh nghiệm cho người dùng!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.LEGEND_SWORD_2.value,
        item_worth_amount = 5000,
        item_worth_type= "D",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 50,
    ),
    Item(
        item_id = "legend_sword_3",
        item_name = "Tử Sát Độc Kiếm",
        item_description = f"Đoản kiếm kịch độc có thể một vung làm rụng toàn bộ vật phẩm quà tặng của kẻ địch!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.LEGEND_SWORD_3.value,
        item_worth_amount = 8000,
        item_worth_type= "D",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 50,
    ),
]
list_legend_weapon_2 = copy.deepcopy(list_legend_weapon_2_p)