
from typing import List, Optional
from datetime import datetime
from CustomEnum.EmojiEnum import EmojiCreation2

class Item:
    def __init__(self, item_id: str, item_name: str, item_description: str, item_type: str, quantity: int, emoji: str, item_worth_amount: int = 5000, item_worth_type: str = "C", item_require_target: bool = False, is_self_usable = False, bonus_exp: int = 0, bonus_dignity: int = 0, rank_required: int = 1):
        self.item_id = item_id
        self.item_name = item_name
        self.item_description = item_description
        self.item_type = item_type
        self.quantity = quantity
        self.emoji = emoji
        self.item_worth_amount = item_worth_amount
        self.item_worth_type = item_worth_type
        self.item_require_target = item_require_target
        self.is_self_usable = is_self_usable
        self.bonus_exp = bonus_exp
        self.bonus_dignity = bonus_dignity
        self.rank_required = rank_required

    def to_dict(self):
        return {
            "item_id": self.item_id,
            "item_name": self.item_name,
            "item_description": self.item_description,
            "item_type": self.item_type,
            "quantity": self.quantity,
            "emoji": self.emoji,
            "item_worth_amount": self.item_worth_amount,
            "item_worth_type": self.item_worth_type,
            "item_require_target": self.item_require_target,
            "is_self_usable": self.is_self_usable,
            "bonus_exp": self.bonus_exp,
            "bonus_dignity": self.bonus_dignity,
            "rank_required": self.rank_required,
        }

    @staticmethod
    def from_dict(data:dict):
        return Item(
                item_id=data.get("item_id", None),
                item_name=data.get("item_name", None),
                item_description=data.get("item_description", None),
                item_type=data.get("item_type", None),
                quantity=data.get("quantity", None),
                emoji=data.get("emoji", None),
                item_worth_amount=data.get("item_worth_amount", None),
                item_worth_type=data.get("item_worth_type", None),
                
                item_require_target=data.get("item_require_target", False),
                is_self_usable=data.get("is_self_usable", False),
                
                bonus_exp=data.get("bonus_exp", 0),
                bonus_dignity=data.get("bonus_dignity", 0),
                rank_required=data.get("rank_required", 1),
            )

#region list gift
list_gift_items = [
    Item(
        item_id = "g_pocky",
        item_name = "Bánh Pocky",
        item_description = "Hộp bánh pocky sẽ giúp bạn tăng kinh nghiệm khi tặng cho người khác!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.GIFT_POCKY.value,
        item_worth_amount = 30,
        item_worth_type= "S",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 0,
        rank_required = 1,
    ),
    Item(
        item_id = "g_flower",
        item_name = "Hoa Xinh",
        item_description = "Bông hoa quý báu có thể giúp tăng nhân phẩm và kinh nghiệm khi tặng cho người khác! Hoặc biết đâu sẽ khiến họ vui hơn thì sao?",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.GIFT_FLOWER.value,
        item_worth_amount = 50,
        item_worth_type= "S",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 5,
        rank_required = 5,
    ),
    Item(
        item_id = "g_chocolate",
        item_name = "Sô cô la",
        item_description = "Một thanh sô cô la ngon lành sẽ làm tăng nhân phẩm và kinh nghiệm khi tặng cho người khác!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.GIFT_CHOCOLATE.value,
        item_worth_amount = 50,
        item_worth_type= "S",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 5,
        bonus_dignity = 10,
        rank_required = 8,
    ),
    Item(
        item_id = "g_stcake",
        item_name = "Bánh kem dâu",
        item_description = "Một miếng bánh kem dâu ngon miệng sẽ làm tăng nhân phẩm và kinh nghiệm khi tặng cho người khác!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.GIFT_STRAW_CAKE.value,
        item_worth_amount = 75,
        item_worth_type= "S",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 10,
        bonus_dignity = 10,
        rank_required = 10,
    ),
    Item(
        item_id = "g_earring",
        item_name = "Khuyên Tai Bạc",
        item_description = "Một đôi khuyên tai xinh xinh cho bạn gái, có thể giúp tăng nhân phẩm và kinh nghiệm khi tặng!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.GIFT_EARRING.value,
        item_worth_amount = 100,
        item_worth_type= "S",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 15,
        bonus_dignity = 5,
        rank_required = 20,
    ),
    Item(
        item_id = "g_sring",
        item_name = "Nhẫn Bạc",
        item_description = "Nhẫn bạc quý phái và đầy thanh lịch, một món quà hoàn hảo có thể giúp tăng nhân phẩm và kinh nghiệm khi tặng cho người khác!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.GIFT_SILVER_RING.value,
        item_worth_amount = 500,
        item_worth_type= "S",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 15,
        bonus_dignity = 10, 
        rank_required = 25,
    ),
    Item(
        item_id = "g_gring",
        item_name = "Nhẫn Vàng",
        item_description = "Nhẫn vàng quý tộc và giàu sang, một món quà hoàn hảo có thể giúp tăng nhân phẩm và kinh nghiệm khi tặng cho người khác!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.GIFT_GOLD_RING.value,
        item_worth_amount = 20,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 30,
        bonus_dignity = 15,
        rank_required = 25,
    ),
    Item(
        item_id = "g_dring",
        item_name = "Nhẫn Kim Cương",
        item_description = "Nhẫn kim cương hào nhoáng và phú quý, một món quà hoàn hảo có thể giúp tăng nhân phẩm và kinh nghiệm khi tặng cho người khác!",
        item_type = "gift",
        quantity = 1,
        emoji = EmojiCreation2.GIFT_DIAMOND_RING.value,
        item_worth_amount = 120,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 30,
        bonus_dignity = 20,
        rank_required = 35,
    ),
]

#region list protection
list_protection_items = [
    Item(
        item_id = "hat_fight_1",
        item_name = "Mũ Chống Đánh",
        item_description = "Mũ bảo hiểm giúp chống bị người khác động thủ, chỉ dùng một lần!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.HELMET_1.value,
        item_worth_amount = 1000,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 15,
    ),
    Item(
        item_id = "hat_fight_2",
        item_name = "Mũ Phản Phệ",
        item_description = "Mũ bảo hiểm giúp đánh ngược lại đứa nào dám đánh luôn cả mình!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.HELMET_2.value,
        item_worth_amount = 6000,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 18,
    ),
    Item(
        item_id = "armor_rob_1",
        item_name = "Giáp Chống Cướp",
        item_description = "Giáp hộ vệ bảo vệ bản thân khỏi lũ cướp ngày!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.ARMOUR_1.value,
        item_worth_amount = 10000,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 18,
    ),
    Item(
        item_id = "armor_rob_2",
        item_name = "Giáp Phản Cướp",
        item_description = "Giáp hộ vệ bảo vệ bản thân khỏi lũ cướp và cướp ngược lại lũ đấy!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.ARMOUR_2.value,
        item_worth_amount = 25000,
        item_worth_type= "S",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 20,
    ),
    Item(
        item_id = "armor_protection_1",
        item_name = "Giáp Da",
        item_description = "Giáp hộ vệ linh hoạt chống vũ khí rẻ tiền, chỉ có 50% bảo vệ thành công!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.ARMOUR_PROTECTION_1.value,
        item_worth_amount = 400,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 35,
    ),
    Item(
        item_id = "armor_protection_2",
        item_name = "Thiết Giáp",
        item_description = "Giáp hộ vệ linh hoạt chống vũ khí!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.ARMOUR_PROTECTION_2.value,
        item_worth_amount = 1000,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 40,
    ),
    Item(
        item_id = "armor_protection_3",
        item_name = "Giáp Nhân Phẩm",
        item_description = "Giáp hộ vệ chống vũ khí và trừ thêm **20** nhân phẩm của kẻ tấn công!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.ARMOUR_PROTECTION_3.value,
        item_worth_amount = 2000,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 40,
    ),
    Item(
        item_id = "armor_protection_4",
        item_name = "Vệ Giáp",
        item_description = f"Giáp hộ vệ chống vũ khí và trừ tiền {EmojiCreation2.COPPER.value} của kẻ tấn công!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.ARMOUR_PROTECTION_4.value,
        item_worth_amount = 3000,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 50,
    ),
    Item(
        item_id = "armor_protection_5",
        item_name = "Giáp Hạng Nặng",
        item_description = f"Giáp hộ vệ chống vũ khí và trừ tiền {EmojiCreation2.SILVER.value} hoặc 5% tỉ lệ tăng rank của kẻ tấn công!",
        item_type = "self_protection",
        quantity = 1,
        emoji = EmojiCreation2.ARMOUR_PROTECTION_5.value,
        item_worth_amount = 4000,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 50,
    ),
]

#region list support item
list_support_items = [
    Item(
        item_id = "rank_up_1",
        item_name = "Thần Dược",
        item_description = "Thần dược tuyệt đối, giúp tăng rank của bản thân lên một cấp!",
        item_type = "self_support",
        quantity = 1,
        emoji = EmojiCreation2.COLORFUL_PILL.value,
        item_worth_amount = 5,
        item_worth_type= "D",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 1,
    ),
    Item(
        item_id = "lock_pick_jail",
        item_name = "Bẻ khoá",
        item_description = "Dụng cụ bẻ khoá, giúp thoát giam lỏng lệnh! Nếu không bị bắt thì không hề vi phạm luật pháp!",
        item_type = "self_support",
        quantity = 1,
        emoji = EmojiCreation2.LOCKPICK.value,
        item_worth_amount = 50,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 20,
    ),
    Item(
        item_id = "out_jail_ticket",
        item_name = "Thẻ Ra Tù",
        item_description = "Chúc mừng bạn đã quay vào ô ra tù miễn phí!",
        item_type = "self_support",
        quantity = 1,
        emoji = EmojiCreation2.TICKET.value,
        item_worth_amount = 100,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 20,
    ),
    Item(
        item_id = "forget_flower",
        item_name = "Hoa Lãng Quên",
        item_description = "Bảo bối giúp lãng quên đi mối tình sâu đậm khi xưa! Sẽ cho phép bạn quen người mới ngay lập tức",
        item_type = "self_support",
        quantity = 1,
        emoji = EmojiCreation2.PURPLE_FLOWER.value,
        item_worth_amount = 500,
        item_worth_type= "G",
        item_require_target = False,
        is_self_usable = True,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 25,
    ),
]
#region list attack items
list_attack_items = [
    Item(
        item_id = "crime_evident",
        item_name = "Bằng Chứng Phạm Tội",
        item_description = f"Hàng cấm, có thể bị chính quyền điều tra ra! Tốt nhất nên nằm trong túi của người khác!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.BLOODY_KNIFE.value,
        item_worth_amount = 500,
        item_worth_type= "S",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 35,
    ),
    Item(
        item_id = "whipping",
        item_name = "Dây Roi",
        item_description = f"Dây roi để quật những kẻ lười biếng phải lao động, và trừ 10 nhân phẩm của kẻ đó!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.WHIP.value,
        item_worth_amount = 500,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 40,
    ),
    Item(
        item_id = "sword_1",
        item_name = "Kiếm Gỗ",
        item_description = "Một thanh kiếm gỗ bình thường, có thể chém bay nhân phẩm của đối thủ!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.SWORD_1.value,
        item_worth_amount = 700,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 45,
    ),
    Item(
        item_id = "sword_2",
        item_name = "Kiếm Đồng",
        item_description = f"Một thanh kiếm đồng rẻ tiền có thể chém bay tiền {EmojiCreation2.COPPER.value} của đối thủ!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.SWORD_2.value,
        item_worth_amount = 800,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 50,
    ),
    Item(
        item_id = "sword_3",
        item_name = "Kiếm Sắt",
        item_description = f"Một thanh kiếm sắt bình thường có thể chém bay tiền {EmojiCreation2.COPPER.value} hoặc điểm nhân phẩm của đối thủ!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.SWORD_3.value,
        item_worth_amount = 1000,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 50,
    ),
    Item(
        item_id = "sword_4",
        item_name = "Kiếm Bạc",
        item_description = f"Một thanh kiếm bạc đắt giá có thể chém bay tiền {EmojiCreation2.SILVER.value} hoặc 10% tăng rank của đối thủ!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.SWORD_4.value,
        item_worth_amount = 2600,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 55,
    ),
    Item(
        item_id = "sword_5",
        item_name = "Kiếm Vàng",
        item_description = f"Một thanh kiếm bạc đắt giá có thể chém bay tiền {EmojiCreation2.SILVER.value} hoặc 15% tăng rank của đối thủ!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.SWORD_5.value,
        item_worth_amount = 5200,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 55,
    ),
    Item(
        item_id = "crime_knife",
        item_name = "Dao Ẩn",
        item_description = f"Một lưỡi dao ẩn có thể chém đứt khả năng phạm tội của đối phương!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.KNIFE.value,
        item_worth_amount = 1200,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 40,
    ),
    Item(
        item_id = "cuff",
        item_name = "Còng Tay",
        item_description = f"Vật phẩm dành riêng cho chính quyền, nhằm trấn áp những kẻ tình nghi phạm tội trong hai tiếng!",
        item_type = "attack",
        quantity = 1,
        emoji = EmojiCreation2.HANDCUFF.value,
        item_worth_amount = 2000,
        item_worth_type= "G",
        item_require_target = True,
        is_self_usable = False,
        bonus_exp = 0,
        bonus_dignity = 0,
        rank_required = 40,
    ),
]